name: Build and Deploy Dashboard 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-staging:
    uses: Flexx-R-D/ops/.github/workflows/build-node-ecr.yml@main
    with:
      aws_ecr_repo_name: flexx-frontend-nextjs-stg
      environment: staging
    secrets: inherit

  build-production:
    # Only build production on main branch
    if: github.ref == 'refs/heads/main'
    needs: build-staging
    uses: Flexx-R-D/ops/.github/workflows/build-node-ecr.yml@main
    with:
      aws_ecr_repo_name: flexx-frontend-nextjs
      environment: production
    secrets: inherit