name: Setup AWS Credentials

on:
  workflow_call:
    inputs:
      aws_region:
        description: 'AWS region'
        required: false
        default: 'us-east-1'
        type: string
      runner_image:
        description: 'The image used to run the workflow'
        required: false
        default: 'ubuntu-22.04'
        type: string
      environment:
        description: 'Environment (staging/production)'
        required: true
        type: string
      aws_ecr_repo_name:
        description: 'ECR registry'
        required: true
        type: string
        default: 'flexx-frontend-nextjs-stg'

jobs:
  setup-credentials:
    runs-on: ${{ inputs.runner_image }}
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify AWS connection
        run: |
          echo "âœ… AWS CLI configured successfully"
          aws sts get-caller-identity --query 'Account' --output text
